// Mock data for Fridos recipes

export interface Recipe {
  id: string;
  name: string;
  time: number; // minutes
  difficulty: 'Kolay' | 'Orta' | 'Zor';
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  mealType: string; // e.g. "Kahvaltı", "Ara Öğünler"
  servings: number;
  tag: 'complete' | 'missing';
  missingCount?: number;
  bgColor: string;
  emoji: string;
  /** Food photo (remote URL). Emoji + bgColor are the fallback. */
  image?: any;
  filters: Array<string>;
  categories: Array<'sana-uygun' | 'bes-yildizli' | 'light-dinner' | 'breakfast-goodies' | 'high-protein' | 'fit-desserts' | 'high-calorie' | 'chef-recommended' | 'low-calorie' | 'practical' | 'breakfast-stars' | 'popular-bowls' | 'fruits' | 'keto' | 'gut-friendly' | 'vegan' | 'gluten-free'>;
  ingredients: Array<{ name: string; quantity: string; owned: boolean }>;
  steps: RecipeStep[];
}

export interface RecipeStep {
  icon?: string;
  text: string;
  duration?: string;
}

export const RECIPES: Recipe[] = [

  {
    id: 'premium_1',
    name: 'Şefin Izgara Somon Tabağı',
    time: 25,
    difficulty: 'Orta',
    kcal: 480,
    protein: 38,
    carbs: 12,
    fat: 28,
    mealType: 'Ana Yemek',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🐟',
    image: require('../assets/images/recipes/recipe_salmon.png'),
    filters: [],
    categories: ["sana-uygun","bes-yildizli","chef-recommended","high-protein"],
    ingredients: [
      { name: "Norveç Somon Fileto", quantity: "200g", owned: true },
      { name: "Taze Kuşkonmaz", quantity: "100g", owned: false },
      { name: "Çeri Domates", quantity: "5-6 Adet", owned: true },
      { name: "Sızma Zeytinyağı", quantity: "2 Yemek Kaşığı", owned: true },
      { name: "Taze Kekik", quantity: "2 Dal", owned: false },
      { name: "Deniz Tuzu", quantity: "1 Çay Kaşığı", owned: true },
      { name: "Taze Çekilmiş Karabiber", quantity: "1 Çay Kaşığı", owned: true },
      { name: "Limon", quantity: "Yarım", owned: true }
    ],
    steps: [
      { text: "Somon filetoyu zeytinyağı, taze kekik, deniz tuzu ve karabiber ile marine edin. Oda sıcaklığında 10 dakika dinlendirin." },
      { text: "Kuşkonmazların sert sap kısımlarını kesin. Çeri domateslerle birlikte fırın tepsisine dizin ve hafifçe yağlayın." },
      { text: "Önceden ısıtılmış döküm tavada somonun deri kısmı alta gelecek şekilde 4 dakika mühürleyin, ardından ters çevirip 3 dakika daha pişirin." },
      { text: "Sebzeleri 200 derece fırında 12 dakika közleyin. Somon ve sebzeleri geniş, şık bir tabakta birleştirip üzerine taze sıkılmış limon suyu gezdirin." }
    ]
  },
  {
    id: 'premium_2',
    name: 'Trüf Mantarlı Artisan Makarna',
    time: 30,
    difficulty: 'Orta',
    kcal: 520,
    protein: 14,
    carbs: 65,
    fat: 22,
    mealType: 'Ana Yemek',
    servings: 2,
    tag: 'complete',
    missingCount: 1,
    bgColor: '#1A1E1C',
    emoji: '🍝',
    image: require('../assets/images/recipes/recipe_pasta.png'),
    filters: [],
    categories: ["sana-uygun","bes-yildizli","chef-recommended"],
    ingredients: [
      { name: "Taze Tagliatelle", quantity: "250g", owned: true },
      { name: "Kestane Mantarı", quantity: "200g", owned: true },
      { name: "Trüf Yağı", quantity: "1 Tatlı Kaşığı", owned: false },
      { name: "Taze Krema", quantity: "1 Çay Bardağı", owned: false },
      { name: "Parmesan Peyniri", quantity: "50g (Rendelenmiş)", owned: true },
      { name: "Sarımsak", quantity: "2 Diş", owned: true },
      { name: "Tereyağı", quantity: "1 Yemek Kaşığı", owned: true },
      { name: "Taze Maydanoz", quantity: "1 Tutam", owned: true }
    ],
    steps: [
      { text: "Taze tagliatelle makarnayı bol tuzlu kaynar suda 3-4 dakika haşlayın. Suyundan yarım çay bardağı ayırıp makarnayı süzün." },
      { text: "Geniş bir tavada tereyağını eritin. İnce dilimlenmiş sarımsak ve mantarları yüksek ateşte soteleyin." },
      { text: "Mantarlar suyunu çekince kremayı, trüf yağını ve ayırdığınız makarna suyunu ekleyin. Sos hafifçe koyulaşana kadar 2 dakika kaynatın." },
      { text: "Makarnaları sosa ekleyin, parmesan peyniriyle bağlayın. Üzerine taze maydanoz serpiştirerek sıcak servis yapın." }
    ]
  },
  {
    id: 'premium_3',
    name: 'Orman Meyveli Fit Cheesecake',
    time: 45,
    difficulty: 'Zor',
    kcal: 280,
    protein: 12,
    carbs: 24,
    fat: 16,
    mealType: 'Tatlı',
    servings: 4,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍰',
    image: require('../assets/images/recipes/recipe_cheesecake.png'),
    filters: [],
    categories: ["sana-uygun","bes-yildizli","fit-desserts","gluten-free"],
    ingredients: [
      { name: "Yulaf Unu", quantity: "1 Su Bardağı", owned: true },
      { name: "Çiğ Badem", quantity: "Yarım Su Bardağı", owned: true },
      { name: "Hurma", quantity: "8 Adet", owned: true },
      { name: "Labne Peyniri (Light)", quantity: "400g", owned: true },
      { name: "Süzme Yoğurt", quantity: "2 Yemek Kaşığı", owned: true },
      { name: "Yumurta", quantity: "2 Adet", owned: true },
      { name: "Bal", quantity: "3 Yemek Kaşığı", owned: true },
      { name: "Taze Orman Meyveleri", quantity: "1 Kase", owned: false }
    ],
    steps: [
      { text: "Taban için: Yulaf unu, badem ve çekirdeksiz hurmaları mutfak robotundan geçirin. Karışımı kelepçeli kalıbın tabanına bastırarak yayın." },
      { text: "İç dolgu için: Labne peyniri, süzme yoğurt ve balı pürüzsüz olana dek çırpın. Yumurtaları tek tek ekleyerek yavaşça karıştırın." },
      { text: "Dolgu karışımını tabanın üzerine dökün. Önceden ısıtılmış 160 derece fırında, fırının tabanına bir kap su koyarak 35-40 dakika pişirin." },
      { text: "Cheesecake soğuduktan sonra buzdolabında en az 4 saat dinlendirin. Servis etmeden önce üzerini taze orman meyveleriyle süsleyin." }
    ]
  },
  {
    id: 'premium_4',
    name: 'Yeşil Canlandırıcı Detox',
    time: 10,
    difficulty: 'Kolay',
    kcal: 110,
    protein: 3,
    carbs: 25,
    fat: 0,
    mealType: 'İçecek',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🧃',
    image: require('../assets/images/recipes/recipe_juice.png'),
    filters: [],
    categories: ["sana-uygun","bes-yildizli","vegan","gut-friendly"],
    ingredients: [
      { name: "Yeşil Elma", quantity: "1 Adet", owned: true },
      { name: "Salatalık", quantity: "1 Adet", owned: true },
      { name: "Kereviz Sapı", quantity: "2 Dal", owned: false },
      { name: "Bebek Ispanak", quantity: "1 Avuç", owned: true },
      { name: "Taze Zencefil", quantity: "1 Başparmak Büyüklüğünde", owned: true },
      { name: "Limon", quantity: "Yarım (Suyu)", owned: true },
      { name: "Taze Nane", quantity: "3-4 Yaprak", owned: true },
      { name: "Buz", quantity: "1 Su Bardağı", owned: true }
    ],
    steps: [
      { text: "Elma, salatalık ve kereviz saplarını bol suda yıkayıp iri parçalar halinde doğrayın." },
      { text: "Doğranmış sebzeleri, ıspanak, soyulmuş zencefil ve limon suyuyla birlikte katı meyve sıkacağından veya güçlü bir blenderdan geçirin." },
      { text: "Blender kullanıyorsanız karışımı ince bir süzgeç veya tülbent yardımıyla süzerek pürüzsüz bir su elde edin." },
      { text: "Hazırladığınız detoks suyunu buz dolu şık bir uzun bardağa alın. Taze nane yaprakları ve limon dilimi ile süsleyerek hemen tüketin." }
    ]
  },

  {
    id: 'gf_1',
    name: 'Bademli Güç Pankeki',
    time: 20,
    difficulty: 'Orta',
    kcal: 340,
    protein: 16,
    carbs: 22,
    fat: 20,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥞',
    filters: [],
    categories: ["gluten-free","breakfast-stars","high-protein","practical"],
    ingredients: [{"name":"Badem Unu","quantity":"1 Su Bardağı","owned":true},{"name":"Yumurta","quantity":"2 Adet","owned":true},{"name":"Olgun Muz","quantity":"Yarım (Ezilmiş)","owned":true},{"name":"Badem Sütü","quantity":"Yarım Su Bardağı","owned":true},{"name":"Kabartma Tozu","quantity":"1 Tatlı Kaşığı","owned":true},{"name":"Vanilya Özütü","quantity":"1 Çay Kaşığı","owned":true},{"name":"Süzme Bal","quantity":"1 Yemek Kaşığı","owned":false},{"name":"Hindistan Cevizi Yağı","quantity":"1 Tatlı Kaşığı","owned":true}],
    steps: [{"text":"Badem unu ve kabartma tozunu geniş bir kapta harmanlayın."},{"text":"Ayrı bir kapta muzu ezin; yumurta, badem sütü, vanilya ve süzme balı ekleyip mikserle pürüzsüzleşene kadar çırpın."},{"text":"Sıvı karışımı kuru malzemelere ekleyip spatula yardımıyla homojen bir kıvam alana kadar yavaşça karıştırın."},{"text":"Yapışmaz tavayı hindistan cevizi yağı ile hafifçe yağlayın. Orta ateşte, harçtan birer kepçe dökerek arkalı önlü altın sarısı olana kadar pişirin."}]
  },
  {
    id: 'gf_2',
    name: 'Dengeli Hurma Kasesi',
    time: 8,
    difficulty: 'Kolay',
    kcal: 310,
    protein: 10,
    carbs: 45,
    fat: 12,
    mealType: 'Ara Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥣',
    filters: [],
    categories: ["gluten-free","fit-desserts","fruits","gut-friendly","popular-bowls"],
    ingredients: [{"name":"Süzme Yoğurt","quantity":"1 Su Bardağı","owned":true},{"name":"Medine Hurması","quantity":"3 Adet (Çekirdeksiz)","owned":true},{"name":"Çiğ Ceviz İçi","quantity":"1 Avuç","owned":false},{"name":"Chia Tohumu","quantity":"1 Tatlı Kaşığı","owned":true},{"name":"Hindistan Cevizi Rendesi","quantity":"1 Tatlı Kaşığı","owned":true},{"name":"Glutensiz Granola","quantity":"2 Yemek Kaşığı","owned":true},{"name":"Toz Tarçın","quantity":"1 Tutam","owned":true}],
    steps: [{"text":"Yoğurdu derin bir kaseye alın, pürüzsüz ve kremsi bir kıvama gelene kadar çırpın."},{"text":"Hurmaları boyuna ince şeritler halinde dilimleyin. Cevizleri bıçak yardımıyla hafifçe irice kıyın."},{"text":"Kasedeki yoğurdun üzerine sırasıyla glutensiz granolayı, hurma dilimlerini ve kırık cevizleri yerleştirin."},{"text":"En son chia tohumu, hindistan cevizi rendesi ve hafif toz tarçın serpiştirerek bekletmeden servis yapın."}]
  },
  {
    id: 'gf_3',
    name: 'Kinoa & Avokadolu Kahvaltı Salatası',
    time: 15,
    difficulty: 'Kolay',
    kcal: 360,
    protein: 14,
    carbs: 25,
    fat: 24,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥗',
    filters: [],
    categories: ["gluten-free","breakfast-stars","gut-friendly","sana-uygun"],
    ingredients: [{"name":"Haşlanmış Kinoa","quantity":"5 Yemek Kaşığı","owned":true},{"name":"Hass Avokado","quantity":"Yarım (Olgun)","owned":true},{"name":"Çeri Domates","quantity":"6 Adet","owned":true},{"name":"Salatalık","quantity":"1 Adet (Küçük)","owned":true},{"name":"Organik Yumurta","quantity":"1 Adet","owned":true},{"name":"Taze Maydanoz ve Dereotu","quantity":"Yarım Demet","owned":true},{"name":"Soğuk Sıkım Zeytinyağı","quantity":"1.5 Yemek Kaşığı","owned":true},{"name":"Taze Limon Suyu","quantity":"1 Yemek Kaşığı","owned":true},{"name":"Deniz Tuzu & Karabiber","quantity":"1 Tutam","owned":true}],
    steps: [{"text":"Yumurtayı kayısı kıvamında kalacak şekilde tam 6 dakika haşlayın ve hemen soğuk suya alıp kabuğunu soyun."},{"text":"Domatesleri ikiye bölün, salatalığı ve avokadoyu küp şeklinde doğrayın. Yeşillikleri ince ince kıyın."},{"text":"Haşlanmış ve soğumuş kinoayı doğradığınız sebzeler ve yeşilliklerle karıştırma kabına aktarın."},{"text":"Zeytinyağı, limon suyu, tuz ve karabiberi çırparak salataya ekleyin ve ezmeden harmanlayın."},{"text":"Salatayı servis tabağına alın, üzerine ikiye bölünmüş yumurtayı yerleştirip servis yapın."}]
  },
  {
    id: 'gf_4',
    name: 'Avokadolu Lor Peynirli Glutensiz Tost',
    time: 10,
    difficulty: 'Kolay',
    kcal: 320,
    protein: 15,
    carbs: 20,
    fat: 20,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥪',
    filters: [],
    categories: ["gluten-free","breakfast-goodies","practical","sana-uygun"],
    ingredients: [{"name":"Glutensiz Karabuğday Ekmeği","quantity":"2 Dilim","owned":true},{"name":"Tatlı Lor Peyniri","quantity":"3 Yemek Kaşığı","owned":true},{"name":"Olgun Avokado","quantity":"Yarım","owned":true},{"name":"Çörek Otu & Pul Biber","quantity":"1er Çay Kaşığı","owned":true},{"name":"Sızma Zeytinyağı","quantity":"1 Tatlı Kaşığı","owned":true},{"name":"Limon Suyu","quantity":"1 Çay Kaşığı","owned":true},{"name":"Tuz","quantity":"1 Tutam","owned":true}],
    steps: [{"text":"Glutensiz ekmek dilimlerini tost makinesinde hafif çıtır olana kadar kızartın."},{"text":"Avokadoyu bir kasede ezip üzerine limon suyu, zeytinyağı ve tuz ekleyerek püre haline getirin."},{"text":"Kızarmış sıcak ekmeklerin üzerine avokado ezmesini eşit şekilde sürün."},{"text":"Üzerine lor peynirini cömertçe paylaştırın, pul biber ve çörek otu serpip dilimleyerek servis edin."}]
  },
  {
    id: 'gf_5',
    name: 'Yumuşak Tavuk & Patates Püresi',
    time: 35,
    difficulty: 'Orta',
    kcal: 490,
    protein: 42,
    carbs: 32,
    fat: 16,
    mealType: 'Akşam Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍗',
    filters: [],
    categories: ["gluten-free","high-protein","bes-yildizli"],
    ingredients: [{"name":"Tavuk Göğsü","quantity":"180 gram","owned":true},{"name":"Patates","quantity":"2 Adet (Orta Boy)","owned":true},{"name":"Taze Sarımsak","quantity":"1 Diş (Ezilmiş)","owned":true},{"name":"Taze Biberiye & Kekik","quantity":"1er Dal","owned":false},{"name":"Tereyağı","quantity":"1 Tatlı Kaşığı","owned":false},{"name":"Ilık Süt","quantity":"Yarım Çay Bardağı","owned":true},{"name":"Muskat Cevizi Rendesi","quantity":"1 Tutam","owned":true},{"name":"Zeytinyağı","quantity":"1 Yemek Kaşığı","owned":true},{"name":"Tuz & Karabiber","quantity":"1 Tutam","owned":true}],
    steps: [{"text":"Tavukları zeytinyağı, ezilmiş sarımsak, kekik, tuz ve karabiberle soslayıp 15 dakika marine edin."},{"text":"Patatesleri soyup küp küp doğrayın, tuzlu suda yumuşayana kadar haşlayıp süzün."},{"text":"Sıcak patatesleri ezerken tereyağı, ılık süt ve bir tutam muskat cevizi rendesi ekleyerek kadifemsi bir püre yapın."},{"text":"Yapışmaz tavayı ısıtın, tavukları arkalı önlü 4-5 dakika (suyunu kaybetmeden) pişirin."},{"text":"Servis tabağının tabanına sıcak patates püresini yayın, üzerine dilimlenmiş tavukları ekleyip taze biberiye ile süsleyin."}]
  },
  {
    id: 'gf_6',
    name: 'Lezzetli Balık Menüsü',
    time: 25,
    difficulty: 'Orta',
    kcal: 410,
    protein: 36,
    carbs: 10,
    fat: 24,
    mealType: 'Akşam Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🐟',
    filters: [],
    categories: ["gluten-free","light-dinner","bes-yildizli","chef-recommended"],
    ingredients: [{"name":"Temizlenmiş Levrek Fileto","quantity":"1 Adet","owned":true},{"name":"Akdeniz Yeşillikleri","quantity":"1 Kase","owned":true},{"name":"Çeri Domates","quantity":"4 Adet","owned":true},{"name":"Kapari","quantity":"1 Tatlı Kaşığı","owned":false},{"name":"Sarımsak","quantity":"1 Diş (Doğranmış)","owned":true},{"name":"Zeytinyağı","quantity":"1.5 Yemek Kaşığı","owned":true},{"name":"Limon Kabuğu Rendesi","quantity":"Yarım Limondan","owned":true},{"name":"Taze Dereotu","quantity":"Yarım Demet","owned":true}],
    steps: [{"text":"Fırını 200 dereceye ısıtın. Levrek filetoyu kurulayıp zeytinyağı, sarımsak, limon kabuğu rendesi, tuz ve ince kıyılmış dereotu ile marine edin."},{"text":"Balığı yağlı kağıt serili fırın tepsisine derisi üstte kalacak şekilde yerleştirin ve 15 dakika fırınlayın."},{"text":"Yeşillikleri yıkayıp kurulayın, ikiye bölünmüş domates ve kapari ile karıştırıp limon-zeytinyağı sosuyla tatlandırın."},{"text":"Fırından çıkan sıcak çıtır balığı yeşillik yatağı üzerinde servis edin."}]
  },
  {
    id: 'gf_7',
    name: 'Gurme Çipura Tabağı',
    time: 40,
    difficulty: 'Zor',
    kcal: 470,
    protein: 38,
    carbs: 12,
    fat: 28,
    mealType: 'Akşam Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🐟',
    filters: [],
    categories: ["gluten-free","chef-recommended","bes-yildizli","light-dinner"],
    ingredients: [{"name":"Taze Çipura (Bütün)","quantity":"1 Adet","owned":true},{"name":"Bebek Patates","quantity":"4 Adet (Kabuklu)","owned":true},{"name":"Limon Dilimleri","quantity":"4 Adet","owned":true},{"name":"Taze Biberiye","quantity":"2 Dal","owned":false},{"name":"Sarımsak","quantity":"2 Diş (Ezilmiş)","owned":true},{"name":"Zeytinyağı","quantity":"2 Yemek Kaşığı","owned":true},{"name":"Kaya Tuzu & Tane Karabiber","quantity":"1er Tutam","owned":true}],
    steps: [{"text":"Çipuranın pullarını temizleyip yıkayın, havlu kağıtla kurulayın. İki yanına bıçakla derin çizikler atın."},{"text":"Balığın içini ve dışını zeytinyağı, tuz ve karabiberle ovalayın. Karın boşluğuna limon dilimleri, biberiye ve sarımsak yerleştirin."},{"text":"Bebek patatesleri yıkayıp ortadan bölün, zeytinyağı ve tuzla soslayıp balığın yanına tepsiye dizin."},{"text":"Önceden ısıtılmış 200 derece fırında, balığın derisi çıtırlaşana ve patatesler yumuşayana kadar yaklaşık 30-35 dakika pişirin."}]
  },
  {
    id: '1',
    name: 'Somonlu Avokado Tost',
    time: 12,
    difficulty: 'Kolay',
    kcal: 450,
    protein: 22,
    carbs: 30,
    fat: 25,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥪',
    filters: [],
    categories: ["breakfast-goodies","breakfast-stars","sana-uygun","bes-yildizli","practical","gluten-free"],
    ingredients: [{"name":"Ekşi Mayalı Ekmek","quantity":"2 Dilim","owned":true},{"name":"Füme Somon","quantity":"50g","owned":true},{"name":"Avokado","quantity":"Yarım","owned":true},{"name":"Limon Suyu","quantity":"1 Tatlı Kaşığı","owned":true},{"name":"Çörek Otu","quantity":"1 Tutam","owned":true}],
    steps: [{"text":"Ekşi mayalı ekmek dilimlerini tost makinesinde çıtırlaşana kadar kızartın."},{"text":"Olgun avokadoyu bir kasede çatal yardımıyla ezin, limon suyu ve tuzla karıştırın."},{"text":"Hazırladığınız avokado püresini kızarmış ekmeklerin üzerine eşit şekilde sürün."},{"text":"Üzerine füme somon dilimlerini yerleştirip çörek otu serpiştirerek servis yapın."}]
  },
  {
    id: '2',
    name: 'Ketojenik Peynirli Omlet',
    time: 10,
    difficulty: 'Kolay',
    kcal: 400,
    protein: 28,
    carbs: 4,
    fat: 30,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍳',
    filters: [],
    categories: ["breakfast-goodies","keto","high-protein","practical","breakfast-stars"],
    ingredients: [{"name":"Yumurta","quantity":"3 Adet","owned":true},{"name":"Cheddar Peyniri","quantity":"40g","owned":true},{"name":"Tereyağı","quantity":"1 Yemek Kaşığı","owned":true},{"name":"Taze Maydanoz","quantity":"3 Dal","owned":true}],
    steps: [{"text":"Yumurtaları derin bir kapta tuz ve karabiber ilavesiyle köpürene kadar çırpın."},{"text":"Tavada tereyağını eritin, çırpılmış yumurtaları döküp orta ateşte pişmeye bırakın."},{"text":"Yumurta hafifçe katılaşınca üzerine rendelenmiş cheddar peynirini ve ince kıyılmış maydanozu ekleyin."},{"text":"Omleti ikiye katlayıp peynirler eriyene kadar 1-2 dakika daha pişirin."}]
  },
  {
    id: '3',
    name: 'Yaban Mersinli Fit Pankek',
    time: 20,
    difficulty: 'Orta',
    kcal: 350,
    protein: 12,
    carbs: 45,
    fat: 10,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥞',
    filters: [],
    categories: ["breakfast-stars","fit-desserts","fruits","low-calorie","practical","gut-friendly"],
    ingredients: [{"name":"Yulaf Unu","quantity":"1 Su Bardağı","owned":true},{"name":"Yağsız Süt","quantity":"1 Su Bardağı","owned":true},{"name":"Yumurta","quantity":"1 Adet","owned":true},{"name":"Yaban Mersini","quantity":"1 Avuç","owned":false},{"name":"Vanilya Özütü","quantity":"1 Çay Kaşığı","owned":true}],
    steps: [{"text":"Yulaf unu, yumurta, süt ve vanilyayı pürüzsüz bir kıvam alana kadar mikserle çırpın."},{"text":"Hazırladığınız hamura taze yaban mersinlerini ekleyip spatula ile yavaşça karıştırın."},{"text":"Yapışmaz tavayı hafifçe yağlayın ve hamurdan küçük yuvarlaklar dökün."},{"text":"Pankeklerin üzeri göz göz olunca ters çevirerek arkalı önlü altın sarısı olana kadar pişirin."}]
  },
  {
    id: '4',
    name: 'Fıstık Ezmeli Yulaf Lapası',
    time: 10,
    difficulty: 'Kolay',
    kcal: 450,
    protein: 18,
    carbs: 60,
    fat: 15,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥣',
    filters: [],
    categories: ["breakfast-goodies","gut-friendly","practical","vegan","high-protein"],
    ingredients: [{"name":"Yulaf Ezmesi","quantity":"5 Yemek Kaşığı","owned":true},{"name":"Badem Sütü","quantity":"1 Su Bardağı","owned":false},{"name":"Fıstık Ezmesi","quantity":"1 Tatlı Kaşığı","owned":true},{"name":"Muz","quantity":"Yarım","owned":false},{"name":"Chia Tohumu","quantity":"1 Çay Kaşığı","owned":true}],
    steps: [{"text":"Yulaf ezmesi ve badem sütünü küçük bir tencereye alıp orta ateşte karıştırarak pişirin."},{"text":"Lapa kıvam alıp kaynamaya başlayınca ocağın altını kapatın."},{"text":"Lapayı kaseye aktarın, üzerine ince dilimlenmiş muz yerleştirin."},{"text":"Fıstık ezmesi ve chia tohumu ekleyerek sıcak servis yapın."}]
  },
  {
    id: '5',
    name: 'Glutensiz Kahvaltı Kasesi',
    time: 15,
    difficulty: 'Kolay',
    kcal: 380,
    protein: 15,
    carbs: 45,
    fat: 12,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥗',
    filters: [],
    categories: ["breakfast-stars","gluten-free","gut-friendly","popular-bowls","fit-desserts"],
    ingredients: [{"name":"Kinoa Patlağı","quantity":"3 Yemek Kaşığı","owned":true},{"name":"Yoğurt","quantity":"1 Kase","owned":true},{"name":"Muz","quantity":"Yarım","owned":true},{"name":"Çiğ Badem","quantity":"1 Avuç","owned":false},{"name":"Bal","quantity":"1 Tatlı Kaşığı","owned":true}],
    steps: [{"text":"Yoğurdu bir kaseye alın ve pürüzsüz kıvama gelene kadar çırpın."},{"text":"Üzerine kinoa patlaklarını eşit bir şekilde serpiştirin."},{"text":"Muz dilimlerini ve bademleri kasenin üzerine estetik şekilde dizin."},{"text":"En son üzerine bal gezdirerek bekletmeden tüketin."}]
  },
  {
    id: '6',
    name: 'Mantar Sote ve Çırpılmış Yumurta',
    time: 15,
    difficulty: 'Kolay',
    kcal: 320,
    protein: 20,
    carbs: 8,
    fat: 22,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍳',
    filters: [],
    categories: ["breakfast-goodies","low-calorie","keto","bes-yildizli","chef-recommended"],
    ingredients: [{"name":"Yumurta","quantity":"2 Adet","owned":true},{"name":"Kültür Mantarı","quantity":"100g","owned":true},{"name":"Zeytinyağı","quantity":"1 Yemek Kaşığı","owned":true},{"name":"Sarımsak","quantity":"1 Diş","owned":true}],
    steps: [{"text":"Mantarları temizleyip ince dilimler halinde doğrayın."},{"text":"Tavada zeytinyağını ısıtıp sarımsak ve mantarları yüksek ateşte soteleyin."},{"text":"Mantarlar suyunu çekince ayrı bir kasede çırptığınız yumurtaları ekleyin."},{"text":"Yumurtalar yumuşak kıvamda pişene kadar karıştırarak soteleyin ve sıcak servis yapın."}]
  },
  {
    id: '7',
    name: 'Izgara Somon ve Kuşkonmaz',
    time: 25,
    difficulty: 'Orta',
    kcal: 550,
    protein: 45,
    carbs: 10,
    fat: 35,
    mealType: 'Ana Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🐟',
    filters: [],
    categories: ["light-dinner","high-protein","keto","chef-recommended","gluten-free","bes-yildizli"],
    ingredients: [{"name":"Somon Fileto","quantity":"200g","owned":true},{"name":"Kuşkonmaz","quantity":"8 Sap","owned":true},{"name":"Limon","quantity":"Yarım","owned":false},{"name":"Zeytinyağı","quantity":"1.5 Yemek Kaşığı","owned":true}],
    steps: [{"text":"Somon filetoyu zeytinyağı, tuz ve karabiberle marine edin."},{"text":"Kuşkonmazların sert uçlarını kırıp hafifçe yağlayın."},{"text":"Somonu ve kuşkonmazları önceden ısıtılmış 200 derece fırında 15-20 dakika pişirin."},{"text":"Servis tabağına alıp üzerine taze limon suyu gezdirin."}]
  },
  {
    id: '8',
    name: 'Tavuklu Sezar Salata',
    time: 20,
    difficulty: 'Kolay',
    kcal: 450,
    protein: 50,
    carbs: 15,
    fat: 20,
    mealType: 'Öğle Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥗',
    filters: [],
    categories: ["light-dinner","high-protein","low-calorie","practical","keto"],
    ingredients: [{"name":"Tavuk Göğsü","quantity":"150g","owned":true},{"name":"Marul","quantity":"1 Demet","owned":true},{"name":"Sezar Sos","quantity":"2 Yemek Kaşığı","owned":true},{"name":"Parmesan","quantity":"1 Yemek Kaşığı","owned":false}],
    steps: [{"text":"Tavuk göğsünü ızgara tavasında arkalı önlü iyice kızarana kadar pişirin."},{"text":"Marulları yıkayıp süzdükten sonra iri parçalar halinde doğrayın."},{"text":"Marulları sezar sos ile harmanlayıp servis tabağına alın."},{"text":"Üzerine dilimlenmiş tavukları yerleştirip parmesan peyniri serpin."}]
  },
  {
    id: '9',
    name: 'Fırında Baharatlı Tavuk Kanatları',
    time: 40,
    difficulty: 'Orta',
    kcal: 780,
    protein: 55,
    carbs: 5,
    fat: 58,
    mealType: 'Akşam Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍗',
    filters: [],
    categories: ["high-calorie","keto","bes-yildizli","high-protein"],
    ingredients: [{"name":"Tavuk Kanat","quantity":"500g","owned":true},{"name":"Zeytinyağı","quantity":"2 Yemek Kaşığı","owned":true},{"name":"Kekik & Toz Kırmızı Biber","quantity":"1 Tatlı Kaşığı","owned":true},{"name":"Sarımsak Tozu","quantity":"1 Çay Kaşığı","owned":false}],
    steps: [{"text":"Kanatları yıkayıp kurulayın, derin bir karıştırma kabına alın."},{"text":"Zeytinyağı, sarımsak tozu, kekik, tuz ve kırmızı biberle iyice harmanlayıp marine edin."},{"text":"Kanatları yağlı kağıt serili fırın tepsisine tek sıra halinde dizin."},{"text":"200 derece fırında üzerleri kızarıp çıtırlaşana kadar yaklaşık 35 dakika pişirin."}]
  },
  {
    id: '10',
    name: 'Kinoalı Ton Balığı Salatası',
    time: 15,
    difficulty: 'Kolay',
    kcal: 420,
    protein: 35,
    carbs: 30,
    fat: 15,
    mealType: 'Öğle Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥗',
    filters: [],
    categories: ["light-dinner","gluten-free","practical","sana-uygun","bes-yildizli","popular-bowls"],
    ingredients: [{"name":"Ton Balığı Konservesi","quantity":"1 Kutu","owned":true},{"name":"Haşlanmış Kinoa","quantity":"4 Yemek Kaşığı","owned":true},{"name":"Çeri Domates","quantity":"5 Adet","owned":true},{"name":"Salatalık","quantity":"1 Adet","owned":true},{"name":"Limon Suyu","quantity":"1 Yemek Kaşığı","owned":true}],
    steps: [{"text":"Domatesleri ve salatalığı yıkayıp küp şeklinde doğrayın."},{"text":"Ton balığının fazla yağını süzgeçte süzün."},{"text":"Bir kapta kinoa, doğranmış sebzeler ve ton balığını birleştirin."},{"text":"Limon suyu, zeytinyağı ve tuz ekleyip ezmeden yavaşça harmanlayın."}]
  },
  {
    id: '11',
    name: 'Etli Mantar Sote',
    time: 30,
    difficulty: 'Orta',
    kcal: 520,
    protein: 45,
    carbs: 12,
    fat: 30,
    mealType: 'Akşam Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥩',
    filters: [],
    categories: ["light-dinner","high-protein","chef-recommended","keto","sana-uygun"],
    ingredients: [{"name":"Kuşbaşı Dana Eti","quantity":"200g","owned":true},{"name":"Kültür Mantarı","quantity":"150g","owned":true},{"name":"Kuru Soğan","quantity":"1 Adet","owned":true},{"name":"Biber","quantity":"1 Adet","owned":true}],
    steps: [{"text":"Etleri tavaya alıp suyunu salıp çekene kadar kısık ateşte pişirin."},{"text":"Üzerine zeytinyağı ve piyazlık doğranmış soğan ile biberi ekleyip soteleyin."},{"text":"Temizlenmiş mantarları iri dilimler halinde ekleyip yüksek ateşte pişmeye bırakın."},{"text":"Mantarlar yumuşayıp soteleşince tuz ve karabiber ilave edip ocaktan alın."}]
  },
  {
    id: '12',
    name: 'Renkli Buda Kasesi (Buddha Bowl)',
    time: 20,
    difficulty: 'Kolay',
    kcal: 480,
    protein: 15,
    carbs: 65,
    fat: 20,
    mealType: 'Öğle Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍲',
    filters: [],
    categories: ["popular-bowls","vegan","gut-friendly","bes-yildizli","low-calorie"],
    ingredients: [{"name":"Tatlı Patates","quantity":"1 Adet","owned":true},{"name":"Haşlanmış Nohut","quantity":"4 Yemek Kaşığı","owned":true},{"name":"Avokado","quantity":"Yarım","owned":true},{"name":"Bebek Ispanak","quantity":"1 Avuç","owned":true},{"name":"Tahin Sos","quantity":"1 Yemek Kaşığı","owned":true}],
    steps: [{"text":"Tatlı patatesi küp küp doğrayıp zeytinyağı ile fırında 20 dakika yumuşayana kadar pişirin."},{"text":"Servis kasesinin tabanına taze ıspanak yapraklarını yerleştirin."},{"text":"Üzerine fırınlanmış patates, nohut ve dilimlenmiş avokadoyu estetik bir şekilde dizin."},{"text":"Üzerine limonlu tahin sosu gezdirerek servis yapın."}]
  },
  {
    id: '13',
    name: 'Tropikal Smoothie Bowl',
    time: 10,
    difficulty: 'Kolay',
    kcal: 310,
    protein: 5,
    carbs: 55,
    fat: 8,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥥',
    filters: [],
    categories: ["popular-bowls","fruits","vegan","low-calorie"],
    ingredients: [{"name":"Dondurulmuş Mango","quantity":"1 Kase","owned":true},{"name":"Hindistan Cevizi Sütü","quantity":"Yarım Su Bardağı","owned":true},{"name":"Chia Tohumu","quantity":"1 Yemek Kaşığı","owned":true},{"name":"Yaban Mersini","quantity":"1 Avuç","owned":false}],
    steps: [{"text":"Mango küplerini and hindistan cevizi sütünü mutfak robotundan geçirin."},{"text":"Yoğun ve pürüzsüz smoothie kıvamına gelince geniş bir kaseye dökün."},{"text":"Üzerini chia tohumu ve taze yaban mersini ile süsleyin."},{"text":"Bekletmeden soğuk olarak tüketin."}]
  },
  {
    id: '14',
    name: 'Yeşil Detoks Çorbası',
    time: 25,
    difficulty: 'Orta',
    kcal: 180,
    protein: 6,
    carbs: 25,
    fat: 5,
    mealType: 'Akşam Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥣',
    filters: [],
    categories: ["gut-friendly","vegan","low-calorie","sana-uygun"],
    ingredients: [{"name":"Taze Ispanak","quantity":"1 Demet","owned":true},{"name":"Kabak","quantity":"1 Adet","owned":true},{"name":"Kereviz Sapı","quantity":"2 Adet","owned":true},{"name":"Soğan","quantity":"1 Adet","owned":true}],
    steps: [{"text":"Sebzeleri yıkayıp iri parçalar halinde doğrayın."},{"text":"Bir tencerede soğan, kabak ve kereviz sapını az suda yumuşayana kadar haşlayın."},{"text":"Pişmeye yakın ıspanakları ekleyip 3-4 dakika daha kaynatın."},{"text":"Çorbayı pürüzsüz olana kadar blenderdan geçirin ve sıcak servis yapın."}]
  },
  {
    id: '15',
    name: 'Fırınlanmış Çıtır Nohut',
    time: 30,
    difficulty: 'Kolay',
    kcal: 250,
    protein: 12,
    carbs: 35,
    fat: 8,
    mealType: 'Ara Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥙',
    filters: [],
    categories: ["practical","vegan","gut-friendly","gluten-free","chef-recommended"],
    ingredients: [{"name":"Haşlanmış Nohut","quantity":"2 Su Bardağı","owned":true},{"name":"Zeytinyağı","quantity":"1 Yemek Kaşığı","owned":true},{"name":"Toz Biber & Kimyon","quantity":"1 Tatlı Kaşığı","owned":true},{"name":"Kaya Tuzu","quantity":"1 Tutam","owned":true}],
    steps: [{"text":"Nohutları süzüp havlu kağıtla tamamen kurulayın (çıtır olması için kuru olmalı)."},{"text":"Bir kasede zeytinyağı, tuz, kimyon ve kırmızı toz biberle nohutları harmanlayın."},{"text":"Yağlı kağıt serili tepsiye nohutları üst üste gelmeyecek şekilde dizin."},{"text":"200 derece fırında kıtırlaşana kadar 25-30 dakika pişirin."}]
  },
  {
    id: '16',
    name: 'Avokadolu Fit Kakaolu Puding',
    time: 10,
    difficulty: 'Kolay',
    kcal: 320,
    protein: 8,
    carbs: 20,
    fat: 25,
    mealType: 'Ara Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍫',
    filters: [],
    categories: ["fit-desserts","keto","vegan","sana-uygun","practical"],
    ingredients: [{"name":"Olgun Avokado","quantity":"1 Adet","owned":true},{"name":"Ham Kakao","quantity":"2 Yemek Kaşığı","owned":true},{"name":"Süzme Bal","quantity":"1 Yemek Kaşığı","owned":false},{"name":"Badem Sütü","quantity":"Çeyrek Su Bardağı","owned":true}],
    steps: [{"text":"Avokadoyu ikiye bölün, çekirdeğini çıkarıp içini kaşıkla robota alın."},{"text":"Kakao, bal ve badem sütünü ekleyerek robotu çalıştırın."},{"text":"Karışım tamamen kremsi ve pürüzsüz olana kadar yüksek devirde çekin."},{"text":"Kaselere paylaştırıp buzdolabında soğuttuktan sonra servis edin."}]
  },
  {
    id: '17',
    name: 'Şekersiz Elmalı Turta Yulafı',
    time: 15,
    difficulty: 'Kolay',
    kcal: 340,
    protein: 10,
    carbs: 60,
    fat: 8,
    mealType: 'Ara Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍎',
    filters: [],
    categories: ["fit-desserts","fruits","gut-friendly","practical"],
    ingredients: [{"name":"Yulaf Ezmesi","quantity":"4 Yemek Kaşığı","owned":true},{"name":"Elma","quantity":"1 Adet (Rendelenmiş)","owned":true},{"name":"Toz Tarçın","quantity":"1 Tatlı Kaşığı","owned":true},{"name":"Süt","quantity":"1 Su Bardağı","owned":true}],
    steps: [{"text":"Yulaf, rende elma ve tarçını süt ile birlikte küçük bir tencereye alın."},{"text":"Kısık ateşte yulaflar sütü tamamen çekene kadar karıştırarak pişirin."},{"text":"Kıvam alan lapayı sıcakken kaseye aktarın."},{"text":"Üzerine ekstra tarçın serpip ceviz içi ile süsleyerek servis yapın."}]
  },
  {
    id: '18',
    name: 'Çilekli Protein Bowl',
    time: 5,
    difficulty: 'Kolay',
    kcal: 280,
    protein: 25,
    carbs: 30,
    fat: 5,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍓',
    filters: [],
    categories: ["fruits","high-protein","popular-bowls","low-calorie","gut-friendly"],
    ingredients: [{"name":"Taze Çilek","quantity":"1 Kase","owned":true},{"name":"Süzme Yoğurt","quantity":"4 Yemek Kaşığı","owned":true},{"name":"Protein Tozu","quantity":"1 Ölçek","owned":false},{"name":"Yulaf Granolası","quantity":"1 Yemek Kaşığı","owned":true}],
    steps: [{"text":"Yoğurt ve protein tozunu pürüzsüz olana kadar bir kapta çırpın."},{"text":"Hazırladığınız karışımı servis kasesine aktarın."},{"text":"Üzerini taze dilimlenmiş çilekler ve granola ile süsleyin."}]
  },
  {
    id: '19',
    name: 'Karpuz & Nane Ferahlığı',
    time: 5,
    difficulty: 'Kolay',
    kcal: 120,
    protein: 2,
    carbs: 28,
    fat: 0,
    mealType: 'Ara Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍉',
    filters: [],
    categories: ["fruits","low-calorie","vegan","practical","keto"],
    ingredients: [{"name":"Karpuz","quantity":"2 Dilim","owned":true},{"name":"Taze Nane Yaprakları","quantity":"5 Yaprak","owned":true},{"name":"Beyaz Peynir","quantity":"30g","owned":true}],
    steps: [{"text":"Çekirdekleri temizlenmiş karpuz dilimlerini lokmalık küpler halinde doğrayın."},{"text":"Nane yapraklarını ince ince kıyın veya elinizle bölün."},{"text":"Karpuz küplerini ve naneyi karıştırıp soğuk servis kasesine alın."}]
  },
  {
    id: '20',
    name: 'Ev Yapımı Gurme Burger',
    time: 40,
    difficulty: 'Zor',
    kcal: 950,
    protein: 55,
    carbs: 65,
    fat: 50,
    mealType: 'Ana Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍔',
    filters: [],
    categories: ["high-calorie","chef-recommended","bes-yildizli","gluten-free"],
    ingredients: [{"name":"Dana Kıyma","quantity":"200g","owned":true},{"name":"Hamburger Ekmeği","quantity":"1 Adet","owned":true},{"name":"Cheddar Peyniri","quantity":"2 Dilim","owned":false},{"name":"Karamelize Soğan","quantity":"2 Yemek Kaşığı","owned":true}],
    steps: [{"text":"Dana kıymayı tuz ve karabiberle yoğurup kalın bir köfte şekli verin."},{"text":"Burger köftesini döküm tavada yüksek ateşte mühürleyerek arkalı önlü pişirin."},{"text":"Pişmesine yakın üzerine cheddar dilimlerini koyup erimesini sağlayın."},{"text":"Hamburger ekmeğini kızartın, köfteyi yerleştirip karamelize soğan ekleyin."}]
  },
  {
    id: '21',
    name: 'Kremalı Mantarlı Makarna',
    time: 25,
    difficulty: 'Orta',
    kcal: 850,
    protein: 20,
    carbs: 90,
    fat: 45,
    mealType: 'Ana Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍝',
    filters: [],
    categories: ["high-calorie","practical","sana-uygun","gut-friendly"],
    ingredients: [{"name":"Makarna","quantity":"Yarım Paket","owned":true},{"name":"Sıvalı Krema","quantity":"1 Kutu","owned":true},{"name":"Kültür Mantarı","quantity":"200g","owned":true},{"name":"Sarımsak","quantity":"1 Diş","owned":true}],
    steps: [{"text":"Makarnayı bol tuzlu kaynar suda dente kıvamında haşlayıp süzün."},{"text":"Ayrı bir tavada zeytinyağı ile sarımsak ve doğranmış mantarları soteleyin."},{"text":"Mantarlar suyunu çekince kremayı ekleyip kısık ateşte 2 dakika tıkırdatın."},{"text":"Süzülen makarnayı krema sosuna ilave edip 1 dakika karıştırarak servis edin."}]
  },
  {
    id: '22',
    name: 'Köz Patlıcanlı Gurme Biftek',
    time: 45,
    difficulty: 'Zor',
    kcal: 720,
    protein: 60,
    carbs: 15,
    fat: 45,
    mealType: 'Akşam Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥩',
    filters: [],
    categories: ["chef-recommended","bes-yildizli","high-protein","keto","popular-bowls"],
    ingredients: [{"name":"Dana Antrikot","quantity":"250g","owned":true},{"name":"Bostan Patlıcan","quantity":"2 Adet","owned":true},{"name":"Tereyağı","quantity":"1 Yemek Kaşığı","owned":true},{"name":"Sarımsak","quantity":"1 Diş","owned":true}],
    steps: [{"text":"Patlıcanları közleyip kabuklarını soyun ve ince ince kıyarak püre yapın."},{"text":"Tavada tereyağını eritin, patlıcan püresi ve ezilmiş sarımsağı ekleyip kavurun."},{"text":"Bifteği döküm tavada yüksek ateşte mühürleyip pişirin."},{"text":"Sıcak patlıcan beğendi yatağında biftek dilimlerini yerleştirip servis yapın."}]
  },
  {
    id: '23',
    name: 'Limonlu Izgara Levrek',
    time: 25,
    difficulty: 'Orta',
    kcal: 410,
    protein: 36,
    carbs: 10,
    fat: 24,
    mealType: 'Akşam Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🐟',
    filters: [],
    categories: ["light-dinner","high-protein","chef-recommended","gluten-free","bes-yildizli"],
    ingredients: [{"name":"Levrek Fileto","quantity":"1 Adet","owned":true},{"name":"Taze Dereotu","quantity":"Yarım Demet","owned":true},{"name":"Limon Dilimleri","quantity":"4 Adet","owned":true},{"name":"Sızma Zeytinyağı","quantity":"1 Yemek Kaşığı","owned":true}],
    steps: [{"text":"Levrek filetoyu yıkayıp kuruladıktan sonra zeytinyağı ile yağlayın."},{"text":"Yağlı kağıt serili tepsiye balığı yerleştirip üzerine limon dilimleri koyun."},{"text":"200 derece önceden ısıtılmış fırında yaklaşık 15-20 dakika fırınlayın."},{"text":"Üzerine taze kıyılmış dereotu serperek Akdeniz yeşillikleriyle servis edin."}]
  },
  {
    id: '24',
    name: 'Köri Soslu Tavuk',
    time: 25,
    difficulty: 'Kolay',
    kcal: 530,
    protein: 42,
    carbs: 18,
    fat: 28,
    mealType: 'Akşam Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍗',
    filters: [],
    categories: ["high-protein","practical","high-calorie"],
    ingredients: [{"name":"Kuşbaşı Tavuk Göğsü","quantity":"200g","owned":true},{"name":"Sıvı Krema","quantity":"Yarım Paket","owned":true},{"name":"Köri Baharatı","quantity":"1 Tatlı Kaşığı","owned":true},{"name":"Renkli Dolmalık Biberler","quantity":"Yarımşar Adet","owned":true}],
    steps: [{"text":"Tavukları yüksek ateşte suyunu çekene kadar tavada soteleyin."},{"text":"Jülyen doğranmış renkli biberleri ekleyip 3-4 dakika daha sotelemeye devam edin."},{"text":"Sıvı krema ve köri baharatını tuz ilavesiyle tavaya dökün."},{"text":"Kısık ateşte sos koyulaşana kadar 2-3 dakika karıştırarak pişirin."}]
  },
  {
    id: '25',
    name: 'Fırınlanmış Somon Şiş',
    time: 20,
    difficulty: 'Orta',
    kcal: 490,
    protein: 38,
    carbs: 12,
    fat: 26,
    mealType: 'Ana Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🐟',
    filters: [],
    categories: ["light-dinner","high-protein","chef-recommended","gluten-free"],
    ingredients: [{"name":"Somon Küpleri","quantity":"180g","owned":true},{"name":"Kiraz Domates","quantity":"6 Adet","owned":true},{"name":"Kırmızı Soğan","quantity":"1 Adet","owned":true},{"name":"Defne Yaprağı","quantity":"4 Adet","owned":true}],
    steps: [{"text":"Somon küplerini zeytinyağı, kekik, tuz ve karabiberle marine edin."},{"text":"Çöp şişlere sırasıyla somon, domates, soğan ve defne yaprağını dizin."},{"text":"Fırın tepsisine dizdiğiniz somon şişleri 200 derecede 15 dakika pişirin."},{"text":"Sıcak limon dilimleri eşliğinde servis tabağında servis yapın."}]
  },
  {
    id: '26',
    name: 'Ispanaklı Keçi Peynirli Omlet',
    time: 10,
    difficulty: 'Kolay',
    kcal: 290,
    protein: 22,
    carbs: 4,
    fat: 20,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍳',
    filters: [],
    categories: ["breakfast-goodies","keto","low-calorie","practical"],
    ingredients: [{"name":"Yumurta","quantity":"2 Adet","owned":true},{"name":"Bebek Ispanak Yaprakları","quantity":"1 Avuç","owned":true},{"name":"Keçi Peyniri","quantity":"30g","owned":true},{"name":"Zeytinyağı","quantity":"1 Tatlı Kaşığı","owned":true}],
    steps: [{"text":"Tavada zeytinyağı ile yıkanmış ıspanak yapraklarını 1 dakika soteleyin."},{"text":"Bir kasede çırpılmış yumurtaları tuz ekleyerek ıspanakların üzerine dökün."},{"text":"Yumurta katılaşmaya başlayınca ufaladığınız keçi peynirini ekleyin."},{"text":"Omleti katlayıp sıcak servis edin."}]
  },
  {
    id: '27',
    name: 'Akdeniz Buda Kasesi',
    time: 20,
    difficulty: 'Kolay',
    kcal: 430,
    protein: 12,
    carbs: 55,
    fat: 16,
    mealType: 'Öğle Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍲',
    filters: [],
    categories: ["popular-bowls","vegan","gut-friendly","low-calorie"],
    ingredients: [{"name":"Haşlanmış Nohut","quantity":"4 Yemek Kaşığı","owned":true},{"name":"Kiraz Domates","quantity":"5 Adet","owned":true},{"name":"Salatalık","quantity":"1 Adet","owned":true},{"name":"Roka & Marul","quantity":"1 Kase","owned":true},{"name":"Sızma Zeytinyağı","quantity":"1 Yemek Kaşığı","owned":true}],
    steps: [{"text":"Yeşillikleri yıkayıp kurulayın ve kasenin tabanına yayın."},{"text":"Nohutları, çeri domatesleri ve salatalık dilimlerini yeşilliklerin üzerine dizin."},{"text":"Sızma zeytinyağı ve taze sıkılmış limon suyunu çırparak kasede gezdirin."},{"text":"İsteğe bağlı çörek otu serpip servis edin."}]
  },
  {
    id: '28',
    name: 'Narlı Bebek Ispanak Salatası',
    time: 10,
    difficulty: 'Kolay',
    kcal: 210,
    protein: 6,
    carbs: 24,
    fat: 12,
    mealType: 'Ara Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥗',
    filters: [],
    categories: ["vegan","low-calorie","fruits","practical","gut-friendly"],
    ingredients: [{"name":"Bebek Ispanak","quantity":"2 Avuç","owned":true},{"name":"Nar Taneleri","quantity":"4 Yemek Kaşığı","owned":true},{"name":"Ceviz İçi","quantity":"1 Avuç","owned":false},{"name":"Nar Ekşisi","quantity":"1 Yemek Kaşığı","owned":true}],
    steps: [{"text":"Bebek ıspanak yapraklarını iyice yıkayıp salata kurutucusunda kurutun."},{"text":"Ispanakları servis kasesine alın, üzerine nar tanelerini serpin."},{"text":"Ceviz içlerini elinizle hafifçe kırarak salatanın üzerine ekleyin."},{"text":"Zeytinyağı ve nar ekşisini bir kapta karıştırıp salatada gezdirin."}]
  },
  {
    id: '29',
    name: 'Acılı Çıtır Tofu Küpleri',
    time: 25,
    difficulty: 'Orta',
    kcal: 310,
    protein: 28,
    carbs: 12,
    fat: 18,
    mealType: 'Öğle Yemeği',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🌶️',
    filters: [],
    categories: ["vegan","high-protein","practical","low-calorie","light-dinner"],
    ingredients: [{"name":"Sert Tofu","quantity":"200g","owned":true},{"name":"Soya Sosu","quantity":"2 Yemek Kaşığı","owned":true},{"name":"Pul Biber","quantity":"1 Yemek Kaşığı","owned":false},{"name":"Susam Yağı","quantity":"1 Tatlı Kaşığı","owned":true}],
    steps: [{"text":"Tofuyu kağıt havlu arasında bastırarak fazla suyundan arındırın."},{"text":"Tofuyu küçük küpler halinde dilimleyip soya sosu ve susam yağıyla karıştırın."},{"text":"Üzerine bol pul biber serpip yağlı kağıt serili tepsiye yerleştirin."},{"text":"200 derece fırında dışı çıtır olana kadar yaklaşık 20 dakika pişirin."}]
  },
  {
    id: '30',
    name: 'Avokadolu Kinoa Salatası',
    time: 15,
    difficulty: 'Kolay',
    kcal: 340,
    protein: 10,
    carbs: 32,
    fat: 18,
    mealType: 'Ara Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥗',
    filters: [],
    categories: ["popular-bowls","gluten-free","vegan","gut-friendly","low-calorie"],
    ingredients: [{"name":"Haşlanmış Kinoa","quantity":"5 Yemek Kaşığı","owned":true},{"name":"Avokado","quantity":"Yarım","owned":true},{"name":"Taze Nane & Maydanoz","quantity":"Çeyrek Demet","owned":true},{"name":"Zeytinyağı","quantity":"1 Yemek Kaşığı","owned":true}],
    steps: [{"text":"Maydanoz ve taze naneyi ince ince kıyın."},{"text":"Avokadoyu küp şeklinde doğrayın."},{"text":"Kinoa, yeşillikler ve avokadoyu bir karıştırma kabında buluşturun."},{"text":"Limon ve zeytinyağı ekleyip hafifçe karıştırarak servis edin."}]
  },
  {
    id: '31',
    name: 'Yoğurtlu Orman Meyveli Parfe',
    time: 8,
    difficulty: 'Kolay',
    kcal: 260,
    protein: 12,
    carbs: 38,
    fat: 6,
    mealType: 'Ara Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍧',
    filters: [],
    categories: ["fruits","breakfast-stars","fit-desserts","gut-friendly"],
    ingredients: [{"name":"Süzme Yoğurt","quantity":"1 Su Bardağı","owned":true},{"name":"Glutensiz Granola","quantity":"2 Yemek Kaşığı","owned":true},{"name":"Taze Ahududu & Böğürtlen","quantity":"1 Avuç","owned":true},{"name":"Süzme Bal","quantity":"1 Tatlı Kaşığı","owned":true}],
    steps: [{"text":"Yoğurdu pürüzsüz olana kadar bir kasede çırpın."},{"text":"Geniş bir bardağın tabanına 2 kaşık yoğurt koyun, üzerine granola ekleyin."},{"text":"Üzerine yoğurt ve taze orman meyveleri ekleyerek katlar oluşturun."},{"text":"En üst kata bal gezdirip soğuk servis yapın."}]
  },
  {
    id: '32',
    name: 'Muzlu Yulaf Lapası',
    time: 10,
    difficulty: 'Kolay',
    kcal: 380,
    protein: 14,
    carbs: 55,
    fat: 12,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥣',
    filters: [],
    categories: ["breakfast-goodies","practical","gut-friendly"],
    ingredients: [{"name":"Yulaf Ezmesi","quantity":"4 Yemek Kaşığı","owned":true},{"name":"Süt","quantity":"1 Su Bardağı","owned":true},{"name":"Olgun Muz","quantity":"Yarım (Dilimlenmiş)","owned":true},{"name":"Ceviz İçi","quantity":"4 Adet","owned":true}],
    steps: [{"text":"Yulaf ezmesini sütle birlikte küçük tencereye alıp pişmeye bırakın."},{"text":"Yulaf sütü çekip yumuşayana kadar karıştırarak pişirin."},{"text":"Lapayı kaseye alın, üzerine muz dilimlerini ve kırılmış cevizleri dizin."},{"text":"Sıcak servis yapın."}]
  },
  {
    id: '33',
    name: 'Yeşil Detoks Suyu',
    time: 5,
    difficulty: 'Kolay',
    kcal: 90,
    protein: 2,
    carbs: 20,
    fat: 0,
    mealType: 'Ara Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🍏',
    filters: [],
    categories: ["fruits","vegan","low-calorie","gut-friendly","practical"],
    ingredients: [{"name":"Yeşil Elma","quantity":"1 Adet","owned":true},{"name":"Kereviz Sapı","quantity":"2 Adet","owned":true},{"name":"Taze Limon","quantity":"Yarım","owned":true},{"name":"Taze Zencefil","quantity":"1 Dilim","owned":true}],
    steps: [{"text":"Elma ve kereviz saplarını yıkayıp iri parçalara bölün."},{"text":"Tüm malzemeleri katı meyve sıkacağına atarak suyunu sıkın."},{"text":"Sıkılan suyu bardağa alıp üzerine buz küpleri ekleyin."},{"text":"Taze ve serin servis edin."}]
  },
  {
    id: '34',
    name: 'Tropikal Mango Smoothie',
    time: 5,
    difficulty: 'Kolay',
    kcal: 180,
    protein: 4,
    carbs: 42,
    fat: 2,
    mealType: 'Ara Öğün',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥤',
    filters: [],
    categories: ["fruits","vegan","low-calorie","practical"],
    ingredients: [{"name":"Taze Mango","quantity":"1 Adet","owned":true},{"name":"Hindistan Cevizi Suyu","quantity":"1 Su Bardağı","owned":true},{"name":"Taze Nane Yaprakları","quantity":"3 Yaprak","owned":true}],
    steps: [{"text":"Mangoyu soyup çekirdeğinden ayırın ve küp doğrayın."},{"text":"Blender kabına mango, soğuk hindistan cevizi suyu ve naneyi alın."},{"text":"Tamamen pürüzsüz olana kadar blenderdan geçirin ve bardağa alın."}]
  },
  {
    id: '35',
    name: 'Ege Usulü Çılbır',
    time: 15,
    difficulty: 'Orta',
    kcal: 320,
    protein: 18,
    carbs: 10,
    fat: 22,
    mealType: 'Kahvaltı',
    servings: 1,
    tag: 'complete',
    missingCount: 0,
    bgColor: '#1A1E1C',
    emoji: '🥚',
    filters: [],
    categories: ["breakfast-stars","high-protein","chef-recommended","sana-uygun"],
    ingredients: [{"name":"Yumurta","quantity":"2 Adet","owned":true},{"name":"Süzme Yoğurt","quantity":"4 Yemek Kaşığı","owned":true},{"name":"Sarımsak","quantity":"1 Diş - Ezilmiş","owned":true},{"name":"Tereyağı","quantity":"1 Tatlı Kaşığı","owned":true},{"name":"Pul Biber","quantity":"1 Tatlı Kaşığı","owned":true}],
    steps: [{"text":"Süzme yoğurt, ezilmiş sarımsak ve tuzu karıştırıp servis tabağının tabanına yayın."},{"text":"Geniş bir tencerede suyu kaynatın, içine 1 yemek kaşığı sirke ekleyip ocağı kısın."},{"text":"Yumurtaları kaynayan suya yavaşça kırıp 3 dakika poşe edin."},{"text":"Poşe yumurtaları süzüp yoğurdun üzerine alın, erimiş tereyağı ve pul biberli sos gezdirin."}]
  }
];

/**
 * Real food photos per recipe (id → URL). The 4 premium recipes keep their
 * bundled local images (require). All other recipes get a unique, dish-matching
 * photo here so cards/detail never fall back to the emoji.
 */
const RECIPE_IMAGES: Record<string, string> = {
  '1': 'https://www.themealdb.com/images/media/meals/ikizdm1763760862.jpg',
  '2': 'https://www.themealdb.com/images/media/meals/hqaejl1695738653.jpg',
  '3': 'https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg',
  '4': 'https://www.themealdb.com/images/media/meals/sng9bm1765320170.jpg',
  '5': 'https://www.themealdb.com/images/media/meals/naqyel1608588563.jpg',
  '6': 'https://loremflickr.com/800/600/scrambled,eggs?lock=6',
  '7': 'https://www.themealdb.com/images/media/meals/prrirc1763781360.jpg',
  '8': 'https://loremflickr.com/800/600/caesar,salad?lock=8',
  '9': 'https://www.themealdb.com/images/media/meals/4hzyvq1763792564.jpg',
  '10': 'https://www.themealdb.com/images/media/meals/yypwwq1511304979.jpg',
  '11': 'https://www.themealdb.com/images/media/meals/pbzcrx1763765096.jpg',
  '12': 'https://www.themealdb.com/images/media/meals/zry07j1763779321.jpg',
  '13': 'https://loremflickr.com/800/600/smoothie,bowl?lock=13',
  '14': 'https://www.themealdb.com/images/media/meals/x2fw9e1560460636.jpg',
  '15': 'https://www.themealdb.com/images/media/meals/tvtxpq1511464705.jpg',
  '16': 'https://www.themealdb.com/images/media/meals/rsqwus1511640214.jpg',
  '17': 'https://www.themealdb.com/images/media/meals/c0gmo31766594751.jpg',
  '18': 'https://www.themealdb.com/images/media/meals/178z5o1585514569.jpg',
  '19': 'https://loremflickr.com/800/600/watermelon?lock=19',
  '20': 'https://www.themealdb.com/images/media/meals/lgmnff1763789847.jpg',
  '21': 'https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg',
  '22': 'https://www.themealdb.com/images/media/meals/vussxq1511882648.jpg',
  '23': 'https://www.themealdb.com/images/media/meals/tqd7s21763780609.jpg',
  '24': 'https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg',
  '25': 'https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg',
  '26': 'https://www.themealdb.com/images/media/meals/yvpuuy1511797244.jpg',
  '27': 'https://loremflickr.com/800/600/mediterranean,bowl?lock=27',
  '28': 'https://www.themealdb.com/images/media/meals/wspuvp1511303478.jpg',
  '29': 'https://www.themealdb.com/images/media/meals/1525874812.jpg',
  '30': 'https://www.themealdb.com/images/media/meals/ji3mho1782499823.jpg',
  '31': 'https://loremflickr.com/800/600/yogurt,parfait?lock=31',
  '32': 'https://www.themealdb.com/images/media/meals/sywswr1511383814.jpg',
  '33': 'https://loremflickr.com/800/600/green,juice?lock=33',
  '34': 'https://www.themealdb.com/images/media/meals/8hx4fi1780087744.jpg',
  '35': 'https://loremflickr.com/800/600/poached,eggs?lock=35',
  'gf_1': 'https://www.themealdb.com/images/media/meals/0206h11699013358.jpg',
  'gf_2': 'https://www.themealdb.com/images/media/meals/hyk47c1762772689.jpg',
  'gf_3': 'https://www.themealdb.com/images/media/meals/fqpqml1764359125.jpg',
  'gf_4': 'https://www.themealdb.com/images/media/meals/1549542994.jpg',
  'gf_5': 'https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg',
  'gf_6': 'https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg',
  'gf_7': 'https://loremflickr.com/800/600/fish,fillet?lock=42',
};

// Apply the photo map (skip recipes that already use a bundled require() image).
RECIPES.forEach(r => {
  if (typeof r.image !== 'number' && RECIPE_IMAGES[r.id]) r.image = RECIPE_IMAGES[r.id];
});

/** Image source usable by <Image>: bundled require() (number) or remote URL (string). */
export function recipeImageSource(image: Recipe['image']) {
  if (image == null) return undefined;
  return typeof image === 'number' ? image : { uri: image as string };
}

export function isRecipeLockedForFree(recipeId: string, limit: number): boolean {
  return RECIPES.findIndex(r => r.id === recipeId) >= limit;
}

export interface Meal {
  type: 'breakfast' | 'lunch' | 'dinner';
  name: string;
  emoji: string;
  time: number;
  kcal: number;
  bg: string;
}

export const MEAL_PLAN: Record<number, Meal[]> = {
  0: [
    { type: 'breakfast', name: 'Çilek & Fındıklı Yulaf Bowl', emoji: '🍓', time: 5, kcal: 764, bg: '#1E1E1E' },
    { type: 'lunch', name: 'Yüksek Proteinli Keto Tabağı', emoji: '🍳', time: 15, kcal: 1004, bg: '#1E1E1E' },
    { type: 'dinner', name: 'Mor Protein Pankeki', emoji: '🥞', time: 20, kcal: 740, bg: '#1E1E1E' },
  ],
  1: [
    { type: 'breakfast', name: 'Çilek & Fındıklı Yulaf Bowl', emoji: '🍓', time: 5, kcal: 764, bg: '#1E1E1E' },
    { type: 'lunch', name: 'Yüksek Proteinli Keto Tabağı', emoji: '🍳', time: 15, kcal: 1004, bg: '#1E1E1E' },
    { type: 'dinner', name: 'Mor Protein Pankeki', emoji: '🥞', time: 20, kcal: 740, bg: '#1E1E1E' },
  ],
  2: [
    { type: 'breakfast', name: 'Çilek & Fındıklı Yulaf Bowl', emoji: '🍓', time: 5, kcal: 764, bg: '#1E1E1E' },
    { type: 'lunch', name: 'Yüksek Proteinli Keto Tabağı', emoji: '🍳', time: 15, kcal: 1004, bg: '#1E1E1E' },
    { type: 'dinner', name: 'Mor Protein Pankeki', emoji: '🥞', time: 20, kcal: 740, bg: '#1E1E1E' },
  ],
  3: [
    { type: 'breakfast', name: 'Çilek & Fındıklı Yulaf Bowl', emoji: '🍓', time: 5, kcal: 764, bg: '#1E1E1E' },
    { type: 'lunch', name: 'Yüksek Proteinli Keto Tabağı', emoji: '🍳', time: 15, kcal: 1004, bg: '#1E1E1E' },
    { type: 'dinner', name: 'Mor Protein Pankeki', emoji: '🥞', time: 20, kcal: 740, bg: '#1E1E1E' },
  ],
  4: [
    { type: 'breakfast', name: 'Çilek & Fındıklı Yulaf Bowl', emoji: '🍓', time: 5, kcal: 764, bg: '#1E1E1E' },
    { type: 'lunch', name: 'Yüksek Proteinli Keto Tabağı', emoji: '🍳', time: 15, kcal: 1004, bg: '#1E1E1E' },
    { type: 'dinner', name: 'Mor Protein Pankeki', emoji: '🥞', time: 20, kcal: 740, bg: '#1E1E1E' },
  ],
  5: [
    { type: 'breakfast', name: 'Çilek & Fındıklı Yulaf Bowl', emoji: '🍓', time: 5, kcal: 764, bg: '#1E1E1E' },
    { type: 'lunch', name: 'Yüksek Proteinli Keto Tabağı', emoji: '🍳', time: 15, kcal: 1004, bg: '#1E1E1E' },
    { type: 'dinner', name: 'Mor Protein Pankeki', emoji: '🥞', time: 20, kcal: 740, bg: '#1E1E1E' },
  ],
  6: [
    { type: 'breakfast', name: 'Çilek & Fındıklı Yulaf Bowl', emoji: '🍓', time: 5, kcal: 764, bg: '#1E1E1E' },
    { type: 'lunch', name: 'Yüksek Proteinli Keto Tabağı', emoji: '🍳', time: 15, kcal: 1004, bg: '#1E1E1E' },
    { type: 'dinner', name: 'Mor Protein Pankeki', emoji: '🥞', time: 20, kcal: 740, bg: '#1E1E1E' },
  ],
};

export const SHOPPING_CATEGORIES = [
  {
    label: '🥬 Sebze & Meyve',
    items: [
      { id: 's1', name: 'Avokado' },
      { id: 's2', name: 'Çilek' },
      { id: 's3', name: 'Mango' },
    ],
  },
  {
    label: '🧀 Süt Ürünleri',
    items: [
      { id: 's4', name: 'Badem Sütü' },
      { id: 's5', name: 'Beyaz Peynir' },
      { id: 's6', name: 'Probiyotik Yoğurt' },
    ],
  },
  {
    label: '🛒 Kiler',
    items: [
      { id: 's7', name: 'Yulaf Ezmesi' },
      { id: 's8', name: 'Çiğ Fındık' },
      { id: 's9', name: 'Chia Tohumu' },
    ],
  },
];

export const INGREDIENTS_DEFAULT = [
  'Yumurta',
  'Avokado',
  'Yoğurt',
  'Muz',
  'Yulaf Ezmesi',
  'Çilek',
  'Tavuk Göğsü',
  'Mantar',
];
